[package]
name = "shitty_lunch_picker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
sqlx = { version = "0.6.3", features = ["postgres", "sqlite", "runtime-tokio-rustls", "macros", "offline", "chrono", "uuid"] }
serde = { version = "1.0.163", features = ["derive"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
ulid = { version = "1.0.0", features = ["serde"] }
serde_json = { version = "1.0.96" }
dotenv = "0.15.0"
chrono = { version = "0.4.26", features = ["serde"] }
dialoguer = "0.10.4"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8.5"
futures = "0.3"
clap = { version = "4.3.1", features = ["derive"] }
anyhow = "1.0"
axum = "0.6.18"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace", "cors", "compression-gzip", "request-id", "util", "propagate-header"] }
hyper = { version = "0.14.13", features = ["full"] }