[package]
name = "shitty_lunch_picker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
sqlx = { version = "0.6.3", features = ["postgres", "sqlite", "runtime-tokio-rustls", "macros", "offline", "chrono", "uuid"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
dotenv = "0.15.0"
chrono = { version = "0.4.26", features = ["serde"] }
dialoguer = "0.10.4"
tracing = "0.1"
tracing-subscriber = "0.3"