[package]
name = "shitty_lunch_picker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls", "macros", "offline", "chrono", "uuid"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
dotenv = "0.15.0"
chrono = { version = "0.4.19", features = ["serde"] }