GET {{url}}
Accept: application/json

###
GET {{url}}health_check
Accept: application/json

###
PUT {{url}}create_recipe
Content-Type: application/json
Accept: */*
Accept-Encoding: */*

{
  "name": "tacos"
}

###
PUT {{url}}create_homie
Content-Type: application/json
Accept: */*
Accept-Encoding: */*

{
  "name": "Hunter"
}
