openapi: 3.0.3
info:
  title: Shitty Lunch Picker
  description: Shitty Lunch Picker
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /:
    get:
      operationId: listVersionsv2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples:
                default:
                  value:
                    {
                      "versions": [ "v2" ]
                    }
  /health_check:
    get:
      operationId: healthCheck
      summary: Health Check
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples:
                default:
                  value:
                    {
                      "status": "OK"
                    }